#!/usr/bin/env python3
"""
soc_deploy.py - SOC Stack Builder

Single-file orchestrator that deploys a full SOC stack via Podman.
Configuration is handled via API after boot to avoid mount issues.
"""

import argparse
import json
import logging
import os
import pathlib
import shutil
import subprocess
import sys
import textwrap
import time

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn
    from rich.table import Table
    HAS_RICH = True
except ImportError:
    HAS_RICH = False

# ---------------------------------------------------------------------------
# Embedded filesystem
# ---------------------------------------------------------------------------

_DOCKER_COMPOSE = """services:

  wazuh.manager:
    image: docker.io/wazuh/wazuh-manager:4.7.0
    container_name: wazuh.manager
    restart: unless-stopped
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=${OPENSEARCH_PASSWORD:-SecretPassword}
      - INDEXER_CERT_VALIDATION=no
    networks:
      - soc-net

  wazuh.indexer:
    image: docker.io/opensearchproject/opensearch:2.10.0
    container_name: wazuh.indexer
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD:-SecretPassword}
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - soc-net

  wazuh-dashboard:
    image: docker.io/wazuh/wazuh-dashboard:4.7.0
    container_name: wazuh-dashboard
    ports:
      - "443:5601"
    environment:
      - OPENSEARCH_HOSTS=https://wazuh.indexer:9200
      - WAZUH_API_URL=https://wazuh.manager
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=${OPENSEARCH_PASSWORD:-SecretPassword}
      - INDEXER_CERT_VALIDATION=no
    depends_on:
      - wazuh.indexer
      - wazuh.manager
    networks:
      - soc-net

  postgres:
    image: docker.io/library/postgres:14-alpine
    container_name: iris-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=iris
      - POSTGRES_PASSWORD=${IRIS_DB_PASSWORD:-iris_db_pass}
      - POSTGRES_DB=iris_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - soc-net

  iris:
    image: ghcr.io/dfir-iris/iriswebapp_app:latest
    container_name: iris
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=iris
      - POSTGRES_PASSWORD=${IRIS_DB_PASSWORD:-iris_db_pass}
      - POSTGRES_DB=iris_db
      - POSTGRES_ADMIN_USER=iris
      - POSTGRES_ADMIN_PASSWORD=${IRIS_DB_PASSWORD:-iris_db_pass}
      - IRIS_SECRET_KEY=${IRIS_SECRET_KEY:-changeme}
      - DOCKERIZED=1
    command: ["/bin/bash", "/iriswebapp/iris-entrypoint.sh"]
    depends_on:
      - postgres
    networks:
      - soc-net

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - soc-net

  shuffle-backend:
    image: docker.io/frikky/shuffle-backend:1.4.1
    container_name: shuffle-backend
    restart: unless-stopped
    ports:
      - "3001:5001"
    environment:
      - SHUFFLE_OPENSEARCH_URL=https://wazuh.indexer:9200
      - SHUFFLE_OPENSEARCH_SKIPSSL_VERIFY=true
      - SHUFFLE_OPENSEARCH_INSECURE=true
      - SHUFFLE_BACKEND_PORT=5001
      - SHUFFLE_DATABASE_TYPE=mongodb
      - SHUFFLE_MONGODB_URL=mongodb://mongodb:27017
    networks:
      - soc-net
    depends_on:
      - mongodb
      - wazuh.indexer

  shuffle-frontend:
    image: docker.io/frikky/shuffle-frontend:1.4.1
    container_name: shuffle-frontend
    restart: unless-stopped
    ports:
      - "3443:80"
    environment:
      - BACKEND_HOSTNAME=shuffle-backend
    networks:
      - soc-net
    depends_on:
      - shuffle-backend

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - soc-net

networks:
  soc-net:
    driver: bridge

volumes:
  wazuh_data:
  opensearch_data:
  postgres_data:
  mongo_data:
  ollama_data:
"""

_ENV_TEMPLATE = textwrap.dedent("""\
# SOC Stack Environment Configuration
# Generated by soc_deploy.py

# Wazuh
WAZUH_API_USER=wazuh-wui
WAZUH_API_PASSWORD={wazuh_password}

# OpenSearch
OPENSEARCH_PASSWORD={opensearch_password}

# DFIR IRIS
IRIS_ADMIN_USER=administrator
IRIS_ADMIN_PASSWORD={iris_password}
IRIS_DB_PASSWORD={iris_db_password}
IRIS_SECRET_KEY={iris_secret}

# Shuffle
SHUFFLE_API_KEY={shuffle_api_key}

# Ollama
OLLAMA_MODEL={ollama_model}
OLLAMA_URL=http://localhost:11434

# Threat Intelligence
VT_API_KEY={vt_key}
OTX_API_KEY={otx_key}
""")

# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------

def write_files(work_dir: pathlib.Path):
    """Write embedded configuration files to work_dir."""
    compose_path = work_dir / "docker-compose.yml"
    compose_path.write_text(_DOCKER_COMPOSE, encoding="utf-8")


def check_prerequisites():
    """Verify that Podman and podman compose are installed."""
    if not shutil.which("podman"):
        print("[FAIL] podman not found")
        sys.exit(1)


def generate_env_file(work_dir: pathlib.Path, vt_key: str, otx_key: str):
    """Generate .env file if it doesn't exist."""
    env_path = work_dir / ".env"
    if env_path.exists():
        return

    import secrets
    import string
    import uuid

    def gen_pw(length=16):
        chars = string.ascii_letters + string.digits
        return "".join(secrets.choice(chars) for _ in range(length))

    content = _ENV_TEMPLATE.format(
        wazuh_password=gen_pw(),
        opensearch_password=gen_pw(),
        iris_password=gen_pw(),
        iris_db_password=gen_pw(),
        iris_secret=gen_pw(32),
        shuffle_api_key=str(uuid.uuid4()),
        ollama_model="mistral:7b",
        vt_key=vt_key,
        otx_key=otx_key,
    )
    env_path.write_text(content, encoding="utf-8")


def compose_up(work_dir: pathlib.Path):
    """Launch the SOC stack."""
    print("\nStarting SOC stack containers...")
    subprocess.run(["podman", "compose", "up", "-d"], cwd=str(work_dir))


def wait_for_health():
    """Wait for all services to become healthy."""
    print("\nWaiting for services to become healthy...")
    try:
        from api_wiring import wait_for_services
        wait_for_services(max_wait=600)
    except Exception as e:
        print(f"Health check failed or timed out: {e}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["deploy", "destroy", "reset", "health"])
    parser.add_argument("--vt-key", default="")
    parser.add_argument("--otx-key", default="")
    parser.add_argument("--work-dir", default=None)
    args = parser.parse_args()

    work_dir = pathlib.Path(args.work_dir or "~/soc-stack").expanduser().resolve()
    work_dir.mkdir(parents=True, exist_ok=True)

    if args.command == "deploy":
        write_files(work_dir)
        check_prerequisites()
        generate_env_file(work_dir, args.vt_key, args.otx_key)
        compose_up(work_dir)
        wait_for_health()
        print("\n[OK] SOC Stack deployment complete.")

    elif args.command == "destroy":
        subprocess.run(["podman", "compose", "down", "-v"], cwd=str(work_dir))

    elif args.command == "reset":
        subprocess.run(["podman", "compose", "down", "-v"], cwd=str(work_dir))
        write_files(work_dir)
        generate_env_file(work_dir, args.vt_key, args.otx_key)
        compose_up(work_dir)
        wait_for_health()

    elif args.command == "health":
        from api_wiring import health_check_all
        health_check_all()

if __name__ == "__main__":
    main()
